FROM node:24-alpine AS build
WORKDIR /app
COPY src/Web/package*.json ./
RUN npm ci
COPY src/Web/ .
RUN npm run build
FROM nginx:alpine
COPY --from=build /app/dist/web/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
